### ISSUE TITLE
Kernel Update

### ISSUE THREAD

**Issue by matthewlscarlson** [mikezackles/linux-beacon-pkgbuild#1]
Do you plan on updating this package sometime in the future so that it uses kernel 5.15+?

**Comment by mikezackles** [comment]
Hi! I updated the firmware on my thinkpad using `fwupd` some time ago, and I don't think I've observed the issue since then using a vanilla kernel. In any case, I will try to put together a tentative `PKGBUILD` for a patched kernel (may not get a chance to build it right away though).

**Comment by mikezackles** [comment]
I've tried to get the ball rolling over at #2, but I'm sure there may be issues. Please feel free to give it a shot with `makepkg` and let me know how it goes.
